### ISSUE TITLE
Setup for CI release

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-collections#491]
The snapshot publish failed because this repository is not currently setup for CI release (there is no sonatype user/password in secrets).

```
   env:
    PGP_PASSPHRASE: 
    SONATYPE_PASSWORD: 
    SONATYPE_USERNAME: 
    PGP_SECRET: ***
```

Linking to https://github.com/typelevel/governance/issues/23.
